### ISSUE TITLE
variable @scale-base is undefined

### ISSUE THREAD

**Issue by cbracco** [chromice/order.less#1]
Hi there,

Thanks for creating this awesome tool! I am trying to use `scale.less` in one of my projects, and I keep getting an the following undefined error during compilation (using `gulp-less`), when I use `font-size: @scale-base;` on the `<html>` or the `<body>` element. It is telling me that `@scale-base` is undefined.

```
ERROR: gulp-less - variable @scale-base is undefined in file <filepath> <line number>
```

I have added your `.use-modular-scale()` mixin to my `mixins.less` file, and I am importing this file in my global imports file before the `.less` file that is using the `.use-modular-scale()` mixin, like so:

```
// main.less
@import url("settings/variables.less");
@import url("settings/mixins.less"); // has .use-modular-scale() mixin
@import url("base/file-using-mixin.less"); // has .use-modular-scale() usage
```

And this is how I am using the mixin:

```
// file-using-mixin.less

// Set the modular scale for this project
.use-modular-scale(
  16px,
  24px,
  (3/4)
);

body {
  font-size: @scale-base;
}
```

I am not sure what I am doing incorrectly. Any help is greatly appreciated!

Thanks,
Chris

**Comment by chromice** [comment]
Hi Chris,

I am confused: the error message says <code>@scale-<strong>size</strong></code> is undefined, while you keep referring to <code>@scale-<strong>base</strong></code>. The `@scale-size` variable is exported by `.get-scale-size()` which in turn is used by `.font-size()` and `.use-baseline-grid()`, if you pass a unitless number as the first argument.

Hope that helps.

**Comment by cbracco** [comment]
@chromice Thank you for the reply. The error message is for `@scale-base`, I had a typo in my original response. I've corrected the error message above.

Is the `@scale-base` variable not accessible because of scoping?

**Comment by cbracco** [comment]
@chromice I am able to replicate this error in a Codepen example, shown here: http://codepen.io/cbracco/pen/RNpgGg?editors=110

**Comment by chromice** [comment]
@cbracco Thanks for the test case! Codepen is using v1.7.5 (http://codepen.io/versions/) which either seem to  have a bug or the version of cider I'm drinking is not compatible with it. ;-)

What version of Less are you using? Are you using the browser or command line variety?

**Comment by chromice** [comment]
@cbracco I've just tested all versions of Less and the minimum version supported is 2.0.0 I will probably bump it to 2.2.0 very soon.

**Comment by cbracco** [comment]
@chromice nailed it! That was the problem. The version of gulp-less that I was using depended on a pre-2.0.0 version of Less. I upgraded gulp-less to the latest version, which subsequently upgraded its Less dependency to 2.2.0, and everything is peachy now. :+1: 

Thanks again for your help!
